name: 'Lib config install blog corredores'
type: module
description: 'config install blog corredores.'
package: 'Liberty'
# Information added by Drupal.org packaging script on 2021-10-10
core_version_requirement: ^8.8 || ^9
