_core:
  default_config_hash: FoTCiVMOlTpj9EU5bUJB7lS8JK2gnnvqh-AdIC0ktBQ
max_links: 2000
cron_generate: true
cron_generate_interval: 0
generate_duration: 10000
entities_per_queue_item: 50
remove_duplicates: true
skip_untranslated: true
base_url: ''
default_variant: default
custom_links_include_images: false
excluded_languages: {  }
enabled_entity_types:
  - node
  - menu_link_content
