_core:
  default_config_hash: ttd8HXcqwSjGgp-fWA3gUA8q4TNvXB0a72pkFlnF56g
hotlink: false
origin: 'https://nonprodportal.hdiseguros.com.co'
origin_dir: sites/default/files
proxy_headers: ''
use_imagecache_root: true
verify: false
excluded_extensions: ''
