_core:
  default_config_hash: eKR4FfUD7Cp3bXamsCz6GAxh0PCLIZNMa65y2kChIh0
langcode: es
site_key: 6LchDo4fAAAAAO4vqcQHzPCMMdVCakaTEFa4PfNA
secret_key: 6LchDo4fAAAAAKKrRrLsO4i9PBLO3QPDaxwcEIBs
verify_hostname: false
use_globally: false
widget:
  theme: light
  type: image
  size: ''
  tabindex: 0
  noscript: false
