_core:
  default_config_hash: dnQK_fXC0n9MPQm65de4VfTTE1I5QMcept0WlMmJxmU
langcode: es
base_url: null
secure_forms: true
all_forms: true
other_forms: ''
form_user_login_form: true
form_user_form: true
form_user_register_form: true
form_user_pass_reset: true
form_user_pass: true
form_comment_form: false
form_node_form: false
form_contact_message_form: false
form_webform_client_form: false
