label: 'Biblioteca de medios'
display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
          tags:
            previous: ‹‹
            next: ››
      fields:
        media_bulk_form:
          action_title: Acción
      filters:
        status:
          expose:
            label: 'Estado de publicación'
          group_info:
            label: Publicado
            group_items:
              1:
                title: Publicado
              2:
                title: 'Sin publicar'
        name:
          expose:
            label: Nombre
        bundle:
          expose:
            label: 'Tipos multimedia'
          group_info:
            label: 'Tipos multimedia'
      sorts:
        created:
          expose:
            label: 'Más recientes primero'
      title: Multimedia
      empty:
        area_text_custom:
          content: 'No hay contenidos multimedia disponibles'
  page:
    display_title: Página
    display_options:
      menu:
        title: Multimedia
  widget:
    display_title: Control
