_core:
  default_config_hash: _UaIWu0_ZD3lUs97wlFC2Koi-o7Bex69Xr9q36nJtkY
langcode: es
enabled_default: 0
default_challenge: recaptcha/reCAPTCHA
description: 'This question is for testing whether or not you are a human visitor and to prevent automated spam submissions.'
administration_mode: false
allow_on_admin_pages: false
add_captcha_description: false
wrong_captcha_response_message: 'La respuesta que ingresó para el código de verificación no fue correcta.'
default_validation: 1
persistence: 1
enable_stats: false
log_wrong_responses: false
