_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
langcode: es
ignored_config_entities:
  - liberty_form.marketing_cloud
  - liberty_form.msn_api
  - liberty_form.vip
  - recaptcha.settings
