_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
langcode: es
module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  auto_entitylabel: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  captcha: 0
  ckeditor: 0
  ckeditor5: 0
  color: 0
  comment: 0
  components: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  contact: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  devel: 0
  dynamic_page_cache: 0
  editor: 0
  emulsify_twig: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  history: 0
  image: 0
  image_captcha: 0
  language: 0
  lib_core: 0
  liberty_api: 0
  liberty_color_header: 0
  liberty_form: 0
  liberty_session: 0
  link: 0
  locale: 0
  maillog: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  mmf_core_fields: 0
  node: 0
  options: 0
  page_cache: 0
  paragraphs_features: 0
  password_policy_character_types: 0
  password_policy_characters: 0
  password_policy_consecutive: 0
  password_policy_length: 0
  path: 0
  path_alias: 0
  permissionspolicy: 0
  purge: 0
  rdf: 0
  recaptcha: 0
  remove_http_headers: 0
  search: 0
  seckit: 0
  securelogin: 0
  security_review: 0
  sftp_client: 0
  shortcut: 0
  stage_file_proxy: 0
  structure_sync: 0
  svg_image: 0
  system: 0
  taxonomy: 0
  text: 0
  textfield_counter: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_field_value: 0
  twig_tweak: 0
  ultimate_cron: 0
  update: 0
  user: 0
  views_ui: 0
  webform: 0
  webform_node: 0
  webform_ui: 0
  pathauto: 1
  password_policy: 10
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  bartik: 0
  seven: 0
  stable: 0
  liberty: 0
  emulsify: 0
  claro: 0
  gin: 0
  classy: 0
profile: standard
