variable_get_key: mc0-l2vdt6kflftg9x1gy29nxsdm.rest.marketingcloudapis.com/
api_service_auth: CKEOA5siFBEcOp4ZKflSzwC4
api_client_id: 3shtoj9owcahj5stc3atlc1t
variable_get_key_auth: mc0-l2vdt6kflftg9x1gy29nxsdm.auth.marketingcloudapis.com/v2/token
