_core:
  default_config_hash: eKR4FfUD7Cp3bXamsCz6GAxh0PCLIZNMa65y2kChIh0
langcode: es
site_key: 6LczF44fAAAAAFff5rci8Ov6d95LJlFdAPVAV4iN
secret_key: 6LczF44fAAAAAI60-xGJhbGlsTUDtoF7Ew42DKu5
verify_hostname: false
use_globally: false
widget:
  theme: light
  type: image
  size: ''
  tabindex: 0
  noscript: false
