_core:
  default_config_hash: wB2h-QBawANCiCVEXy6bJjiDfvZY6EONZ6-wRB_RYQc
langcode: es
hotlink: false
origin: 'http://aliados-nonprod.libertyseguros.co'
origin_dir: sites/sponsors/files
use_imagecache_root: true
verify: true
