_core:
  default_config_hash: zJS1GknUylh656CJSNXOupqKSqm6Xw200h1cq1eI970
langcode: es
enabled: true
timeout: 172800
max_timeout: 172800
padding: 20
no_individual_logout_threshold: false
role_logout: false
role_logout_max: false
redirect_url: /user/login
no_dialog: false
message: 'Su sesión está a punto de caducar. ¿Quieres reiniciarlo?'
inactivity_message: 'Se le ha cerrado la sesión debido a la inactividad.'
inactivity_message_type: status
modal_width: 450
enforce_admin: false
jstimer_format: '%hours%:%mins%:%secs%'
jstimer_js_load_option: false
use_alt_logout_method: false
use_watchdog: true
dialog_title: 'Liberty Seguros Alert'
disable_buttons: false
yes_button: ''
no_button: ''
whitelisted_ip_addresses: ''
