<<<<<<< HEAD
uuid: 54c5c7c9-d0e0-4473-b89e-48f1fda713c8
=======
uuid: 89a1112a-a84f-4651-85b7-31d150de5065
>>>>>>> main
langcode: es
status: true
dependencies:
  config:
    - field.field.paragraph.lib_tabs.field_lib_p_items
    - paragraphs.paragraphs_type.lib_tabs
  module:
    - paragraphs
<<<<<<< HEAD
=======
    - paragraphs_features
>>>>>>> main
id: paragraph.lib_tabs.default
targetEntityType: paragraph
bundle: lib_tabs
mode: default
content:
  field_lib_p_items:
    type: paragraphs
    weight: 0
    region: content
    settings:
      title: 'Tab item'
      title_plural: 'Tab items'
      edit_mode: closed
      closed_mode: summary
      autocollapse: all
      closed_mode_threshold: 0
      add_mode: dropdown
      form_display_mode: default
      default_paragraph_type: lib_tab_item
      features:
        add_above: '0'
        collapse_edit_all: collapse_edit_all
        duplicate: duplicate
<<<<<<< HEAD
    third_party_settings: {  }
=======
    third_party_settings:
      paragraphs_features:
        add_in_between: false
        add_in_between_link_count: 3
        delete_confirmation: false
        split_text: false
        show_drag_and_drop: true
>>>>>>> main
hidden:
  created: true
  status: true
