<<<<<<< HEAD
uuid: 0a9467b4-d635-48bd-a680-d7b05f214713
=======
uuid: 6923cbef-e66f-4ab9-845d-e7f858229a62
>>>>>>> main
langcode: es
status: true
dependencies:
  config:
    - field.field.paragraph.card_media.field_lib_heading
    - field.field.paragraph.card_media.field_media_mmedia
    - paragraphs.paragraphs_type.card_media
id: paragraph.card_media.default
targetEntityType: paragraph
bundle: card_media
mode: default
content:
  field_lib_heading:
    type: string
    label: hidden
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 0
    region: content
  field_media_mmedia:
    type: entity_reference_entity_view
    label: hidden
    settings:
      view_mode: default
      link: false
    third_party_settings: {  }
    weight: 1
    region: content
hidden:
  search_api_excerpt: true
