<<<<<<< HEAD
uuid: 343dfe6f-83ea-4a64-86fa-96472e23f87b
=======
uuid: f8e6eacc-267e-43a5-9998-a69bf810cd02
>>>>>>> main
langcode: es
status: true
dependencies:
  config:
    - core.entity_view_mode.paragraph.lib_plan
    - field.field.paragraph.lib_card.field_lib_body
    - field.field.paragraph.lib_card.field_lib_heading
    - field.field.paragraph.lib_card.field_lib_item_list
    - field.field.paragraph.lib_card.field_lib_link
    - field.field.paragraph.lib_card.field_lib_media_icon
    - field.field.paragraph.lib_card.field_lib_media_image
    - paragraphs.paragraphs_type.lib_card
  module:
    - layout_builder
    - link
third_party_settings:
  layout_builder:
    enabled: false
    allow_custom: false
id: paragraph.lib_card.lib_plan
targetEntityType: paragraph
bundle: lib_card
mode: lib_plan
content:
  field_lib_heading:
    type: string
    label: hidden
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 0
    region: content
  field_lib_item_list:
    type: string
<<<<<<< HEAD
    label: inline
=======
    label: hidden
>>>>>>> main
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 2
    region: content
  field_lib_link:
    type: link_separate
    label: hidden
    settings:
      trim_length: 80
      url_only: false
      url_plain: false
      rel: ''
      target: ''
    third_party_settings: {  }
    weight: 1
    region: content
hidden:
  field_lib_body: true
  field_lib_media_icon: true
  field_lib_media_image: true
  search_api_excerpt: true
