_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
langcode: es
module:
  ace_editor: 0
  addtoany: 0
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  ape: 0
  autologout: 0
  backup_migrate: 0
  ban: 0
  better_exposed_filters: 0
  blazy: 0
  block: 0
  block_class: 0
  block_content: 0
  breakpoint: 0
  captcha: 0
  checklistapi: 0
  ckeditor: 0
  ckeditor_videodetector: 0
  condition_query: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  config_update: 0
  consumers: 0
  contact: 0
  contact_storage: 0
  content_moderation: 0
  contextual: 0
  core_context: 0
  crop: 0
  csv_serialization: 0
  ctools: 0
  ctools_block: 0
  datetime: 0
  dblog: 0
  diff: 0
  ds_switch_view_mode: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  editor_advanced_link: 0
  embed: 0
  emulsify_twig: 0
  entity_block: 0
  entity_browser: 0
  entity_browser_block: 0
  entity_embed: 0
  entity_reference_revisions: 0
  entityqueue: 0
  esn_layouts: 0
  facets: 0
  features: 0
  features_ui: 0
  field: 0
  field_group: 0
  field_layout: 0
  field_ui: 0
  file: 0
  filter: 0
  geolocation: 0
  geolocation_google_maps: 0
  geolocation_google_places_api: 0
  gin_lb: 0
  gin_toolbar: 0
  google_analytics: 0
  help: 0
  http_cache_control: 0
  image: 0
  image_captcha: 0
  image_widget_crop: 0
  inline_block_title_automatic: 0
  inline_entity_form: 0
  jquery_ui: 0
  jquery_ui_accordion: 0
  jquery_ui_autocomplete: 0
  jquery_ui_datepicker: 0
  jquery_ui_draggable: 0
  jquery_ui_droppable: 0
  jquery_ui_menu: 0
  jquery_ui_slider: 0
  jquery_ui_tabs: 0
  jquery_ui_touch_punch: 0
  jsonapi: 0
  language: 0
  layout_builder: 0
  layout_builder_additions: 0
  layout_builder_browser: 0
  layout_builder_restrictions: 0
  layout_builder_save_and_edit: 0
  layout_builder_styles: 0
  layout_discovery: 0
  layout_library: 0
  li_news: 0
  lib_cf: 0
  lib_core: 0
  lib_ls: 0
  lib_microsites: 0
  lib_migrate: 0
  lib_quoting: 0
  lib_red_medica: 0
  lib_rm: 0
  liberty_claims: 0
  libraries: 0
  lightning_api: 0
  lightning_contact_form: 0
  lightning_core: 0
  lightning_landing_page: 0
  lightning_layout: 0
  lightning_media: 0
  lightning_media_audio: 0
  lightning_media_document: 0
  lightning_media_image: 0
  lightning_media_slideshow: 0
  lightning_media_twitter: 0
  lightning_media_video: 0
  lightning_page: 0
  lightning_roles: 0
  lightning_scheduler: 0
  lightning_search: 0
  lightning_workflow: 0
  link: 0
  link_attributes: 0
  link_class: 0
  locale: 0
  mailsystem: 0
  maxlength: 0
  media: 0
  media_entity_instagram: 0
  media_entity_twitter: 0
  media_library: 0
  memcache: 0
  menu_link_attributes: 0
  menu_ui: 0
  metatag: 0
  metatag_google_cse: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  migrate: 0
  migrate_spreadsheet: 0
  mimemail: 0
  moderation_sidebar: 0
  mysql: 0
  node: 0
  oauth2_client: 0
  openapi: 0
  openapi_jsonapi: 0
  openapi_rest: 0
  openapi_ui: 0
  openapi_ui_redoc: 0
  openapi_ui_swagger: 0
  options: 0
  page_cache: 0
  pager_serializer: 0
  panelizer: 0
  panelizer_quickedit: 0
  panels: 0
  panels_ipe: 0
  paragraphs_browser: 0
  paragraphs_features: 0
  password_policy_characters: 0
  password_policy_length: 0
  path: 0
  path_alias: 0
  phpmailer_smtp: 0
  quickedit: 0
  rdf: 0
  recaptcha: 0
  redirect: 0
  remove_http_headers: 0
  removeredmedicaspecialties: 0
  responsive_image: 0
  rest: 0
  restui: 0
  schemata: 0
  schemata_json_schema: 0
  search: 0
  search_api: 0
  search_api_autocomplete: 0
  search_api_db: 0
  search_api_solr: 0
  search_api_solr_autocomplete: 0
  seckit: 0
  serialization: 0
  shortcut: 0
  shs: 0
  simple_oauth: 0
  simple_sitemap: 0
  slick: 0
  slick_entityreference: 0
  slick_ui: 0
  slick_views: 0
  social_media_links: 0
  svg_image: 0
  svg_image_field: 0
  svg_image_field_media_bundle: 0
  syslog: 0
  system: 0
  taxonomy: 0
  tb_megamenu: 0
  text: 0
  token: 0
  toolbar: 0
  twig_field_value: 0
  twig_tweak: 0
  ultimate_cron: 0
  update: 0
  upgrade_rector: 0
  upgrade_status: 0
  user: 0
  video_embed_field: 0
  video_embed_media: 0
  views_data_export: 0
  views_field_view: 0
  views_infinite_scroll: 0
  views_ui: 0
  viewsreference: 0
  webform: 0
  webform_access: 0
  webform_image_select: 0
  webform_node: 0
  webform_rest: 0
  webform_submission_export_import: 0
  webform_submission_log: 0
  webform_templates: 0
  webform_ui: 0
  workflows: 0
  yaml_editor: 0
  ds: 1
  manage_display: 1
  menu_link_content: 1
  pathauto: 1
  webform_bootstrap: 1
  content_translation: 10
  password_policy: 10
  views: 10
  paragraphs: 11
  minimal: 1000
theme:
  stable: 0
  bartik: 0
  seven: 0
  cog: 0
  liberty_public: 0
  claro: 0
  gin: 0
profile: minimal
