<<<<<<< HEAD
uuid: a6b5ff12-669a-4896-805a-84809b7fa8ba
=======
uuid: cc41a05d-2ff7-45a8-b0ad-92f72ddbc214
>>>>>>> main
langcode: es
status: true
dependencies:
  config:
    - field.field.taxonomy_term.talleres_chevrolet.field_aixis
    - field.field.taxonomy_term.talleres_chevrolet.field_ciudad
    - field.field.taxonomy_term.talleres_chevrolet.field_cod_ciudad
    - field.field.taxonomy_term.talleres_chevrolet.field_codtaller
    - field.field.taxonomy_term.talleres_chevrolet.field_direccion
    - field.field.taxonomy_term.talleres_chevrolet.field_email
    - field.field.taxonomy_term.talleres_chevrolet.field_nit
    - field.field.taxonomy_term.talleres_chevrolet.field_sucursal
    - field.field.taxonomy_term.talleres_chevrolet.field_telefono
    - taxonomy.vocabulary.talleres_chevrolet
  module:
<<<<<<< HEAD
    - path
=======
    - field_layout
    - layout_discovery
third_party_settings:
  field_layout:
    id: layout_onecol
    settings:
      label: ''
>>>>>>> main
id: taxonomy_term.talleres_chevrolet.default
targetEntityType: taxonomy_term
bundle: talleres_chevrolet
mode: default
content:
  field_aixis:
    type: string_textfield
    weight: 2
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  field_ciudad:
    type: string_textfield
<<<<<<< HEAD
    weight: 5
=======
    weight: 1
>>>>>>> main
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  field_cod_ciudad:
    type: string_textfield
<<<<<<< HEAD
    weight: 6
=======
    weight: 3
>>>>>>> main
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  field_codtaller:
    type: string_textfield
<<<<<<< HEAD
    weight: 1
=======
    weight: 4
>>>>>>> main
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  field_direccion:
    type: string_textfield
<<<<<<< HEAD
    weight: 4
=======
    weight: 5
>>>>>>> main
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  field_email:
    type: string_textfield
<<<<<<< HEAD
    weight: 7
=======
    weight: 6
>>>>>>> main
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  field_nit:
    type: string_textfield
<<<<<<< HEAD
    weight: 3
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  field_sucursal:
    type: string_textfield
    weight: 9
=======
    weight: 7
>>>>>>> main
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  field_telefono:
    type: string_textfield
    weight: 8
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  name:
    type: string_textfield
    weight: 0
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
<<<<<<< HEAD
  path:
    type: path
    weight: 11
    region: content
    settings: {  }
    third_party_settings: {  }
  status:
    type: boolean_checkbox
    weight: 10
    region: content
    settings:
      display_label: true
    third_party_settings: {  }
hidden:
  description: true
  langcode: true
=======
hidden:
  description: true
  field_sucursal: true
  langcode: true
  path: true
  status: true
>>>>>>> main
