<<<<<<< HEAD
uuid: 7ba65037-0683-45ef-99b0-056ed227a31e
=======
uuid: 00722cee-e409-4c61-a434-1a3a87808377
>>>>>>> main
langcode: es
status: true
dependencies:
  config:
    - field.field.paragraph.lib_banner_promo_icons.field_lib_heading
    - field.field.paragraph.lib_banner_promo_icons.field_lib_hero_style
    - field.field.paragraph.lib_banner_promo_icons.field_lib_link
    - field.field.paragraph.lib_banner_promo_icons.field_lib_media_image
    - field.field.paragraph.lib_banner_promo_icons.field_lib_p_items
    - field.field.paragraph.lib_banner_promo_icons.field_lib_summary
    - paragraphs.paragraphs_type.lib_banner_promo_icons
  module:
    - entity_reference_revisions
    - link
    - options
id: paragraph.lib_banner_promo_icons.default
targetEntityType: paragraph
bundle: lib_banner_promo_icons
mode: default
content:
  field_lib_heading:
    type: string
    label: hidden
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 4
    region: content
  field_lib_hero_style:
    type: list_key
    label: hidden
    settings: {  }
    third_party_settings: {  }
    weight: 2
    region: content
  field_lib_link:
    type: link
    label: hidden
    settings:
      trim_length: 80
      url_only: false
      url_plain: false
      rel: ''
      target: ''
    third_party_settings: {  }
    weight: 3
    region: content
  field_lib_media_image:
    type: entity_reference_entity_view
    label: hidden
    settings:
<<<<<<< HEAD
      view_mode: '3_1'
=======
      view_mode: lib_3_1
>>>>>>> main
      link: false
    third_party_settings: {  }
    weight: 0
    region: content
  field_lib_p_items:
    type: entity_reference_revisions_entity_view
    label: hidden
    settings:
      view_mode: default
      link: ''
    third_party_settings: {  }
    weight: 1
    region: content
  field_lib_summary:
    type: basic_string
    label: hidden
    settings: {  }
    third_party_settings: {  }
    weight: 5
    region: content
hidden:
  search_api_excerpt: true
