<<<<<<< HEAD
uuid: 6d065e31-aed6-4e3e-9938-a93fef7cabb0
=======
uuid: dc65990a-ed51-4158-b774-d8c0b62ce3e8
>>>>>>> main
langcode: es
status: true
dependencies:
  config:
    - field.field.paragraph.lib_card_list_out.field_lib_card_style
    - field.field.paragraph.lib_card_list_out.field_lib_columns
    - field.field.paragraph.lib_card_list_out.field_lib_heading
<<<<<<< HEAD
    - field.field.paragraph.lib_card_list_out.field_lib_p_items
=======
    - field.field.paragraph.lib_card_list_out.field_lib_p_card_items
>>>>>>> main
    - paragraphs.paragraphs_type.lib_card_list_out
  module:
    - entity_reference_revisions
    - options
id: paragraph.lib_card_list_out.default
targetEntityType: paragraph
bundle: lib_card_list_out
mode: default
content:
  field_lib_card_style:
    type: list_default
    label: hidden
    settings: {  }
    third_party_settings: {  }
    weight: 3
    region: content
  field_lib_columns:
    type: list_default
    label: hidden
    settings: {  }
    third_party_settings: {  }
    weight: 1
    region: content
  field_lib_heading:
    type: string
    label: hidden
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 0
    region: content
<<<<<<< HEAD
  field_lib_p_items:
=======
  field_lib_p_card_items:
>>>>>>> main
    type: entity_reference_revisions_entity_view
    label: hidden
    settings:
      view_mode: default
      link: ''
    third_party_settings: {  }
    weight: 2
    region: content
hidden:
  search_api_excerpt: true
