<<<<<<< HEAD
uuid: fc3244f6-bad0-47b5-b41c-15a697909928
=======
uuid: cd3d5da7-daf1-4fb0-a538-2b5c6453afed
>>>>>>> main
langcode: es
status: true
dependencies:
  config:
    - field.field.media.vector_image.field_media_in_library
    - field.field.media.vector_image.field_media_svg
    - media.type.vector_image
  module:
    - path
    - svg_image_field
<<<<<<< HEAD
=======
_core:
  default_config_hash: buPLYcuyN2yMLwnjERMFAqXNU9hBOF8W1AbWVPUeKnI
>>>>>>> main
id: media.vector_image.default
targetEntityType: media
bundle: vector_image
mode: default
content:
  created:
    type: datetime_timestamp
<<<<<<< HEAD
    weight: 3
=======
    weight: 2
>>>>>>> main
    region: content
    settings: {  }
    third_party_settings: {  }
  field_media_svg:
    type: svg_image_field_widget
    weight: 0
    region: content
    settings:
      progress_indicator: throbber
      preview_image_max_width: 300
      preview_image_max_height: 300
    third_party_settings: {  }
  langcode:
    type: language_select
    weight: 2
    region: content
    settings:
      include_locked: true
    third_party_settings: {  }
  path:
    type: path
<<<<<<< HEAD
    weight: 4
=======
    weight: 3
>>>>>>> main
    region: content
    settings: {  }
    third_party_settings: {  }
  revision_log_message:
    type: string_textarea
<<<<<<< HEAD
    weight: 6
=======
    weight: 25
>>>>>>> main
    region: content
    settings:
      rows: 4
      placeholder: ''
    third_party_settings: {  }
  status:
    type: boolean_checkbox
<<<<<<< HEAD
    weight: 5
=======
    weight: 4
>>>>>>> main
    region: content
    settings:
      display_label: true
    third_party_settings: {  }
  uid:
    type: entity_reference_autocomplete
    weight: 1
    region: content
    settings:
      match_operator: CONTAINS
      match_limit: 10
      size: 60
      placeholder: ''
    third_party_settings: {  }
hidden:
  field_media_in_library: true
  name: true
