<<<<<<< HEAD
uuid: 2a6cdfba-3354-4096-82ce-64f1f72ec8ec
=======
uuid: 7cd27bec-f41a-445d-93c2-9c18a41c039d
>>>>>>> main
langcode: es
status: true
dependencies:
  config:
    - field.field.paragraph.card_grid_accordion.field_grid_single
    - field.field.paragraph.card_grid_accordion.field_title_card
    - paragraphs.paragraphs_type.card_grid_accordion
  module:
    - entity_reference_revisions
    - text
id: paragraph.card_grid_accordion.default
targetEntityType: paragraph
bundle: card_grid_accordion
mode: default
content:
  field_grid_single:
    type: entity_reference_revisions_entity_view
<<<<<<< HEAD
    label: above
=======
    label: hidden
>>>>>>> main
    settings:
      view_mode: default
      link: ''
    third_party_settings: {  }
    weight: 1
    region: content
  field_title_card:
    type: text_default
<<<<<<< HEAD
    label: above
=======
    label: hidden
>>>>>>> main
    settings: {  }
    third_party_settings: {  }
    weight: 0
    region: content
hidden:
  search_api_excerpt: true
