<<<<<<< HEAD
uuid: 4deab773-4903-4ed5-978e-32495b16373b
=======
uuid: c6d11d7c-64ce-4794-b417-e16fb486e176
>>>>>>> main
langcode: es
status: true
dependencies:
  config:
    - field.field.paragraph.lib_card_list.field_lib_heading
    - field.field.paragraph.lib_card_list.field_lib_link
    - field.field.paragraph.lib_card_list.field_lib_p_items
    - field.field.paragraph.lib_card_list.field_lib_summary
    - paragraphs.paragraphs_type.lib_card_list
  module:
    - link
    - paragraphs
<<<<<<< HEAD
=======
    - paragraphs_features
>>>>>>> main
id: paragraph.lib_card_list.default
targetEntityType: paragraph
bundle: lib_card_list
mode: default
content:
  field_lib_heading:
    type: string_textfield
    weight: 1
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  field_lib_link:
    type: link_default
    weight: 3
    region: content
    settings:
      placeholder_url: ''
      placeholder_title: ''
    third_party_settings: {  }
  field_lib_p_items:
    type: paragraphs
    weight: 0
    region: content
    settings:
<<<<<<< HEAD
      title: Párrafo
      title_plural: Parráfos
      edit_mode: open
      closed_mode: summary
      autocollapse: none
      closed_mode_threshold: 0
      add_mode: dropdown
      form_display_mode: default
      default_paragraph_type: ''
      features:
        collapse_edit_all: collapse_edit_all
        duplicate: duplicate
    third_party_settings: {  }
=======
      title: Card
      title_plural: Cards
      edit_mode: open
      closed_mode: summary
      autocollapse: all
      closed_mode_threshold: 0
      add_mode: dropdown
      form_display_mode: default
      default_paragraph_type: lib_card_list
      features:
        add_above: '0'
        collapse_edit_all: collapse_edit_all
        duplicate: duplicate
    third_party_settings:
      paragraphs_features:
        add_in_between: false
        add_in_between_link_count: 3
        delete_confirmation: false
        split_text: false
        show_drag_and_drop: true
>>>>>>> main
  field_lib_summary:
    type: string_textarea
    weight: 2
    region: content
    settings:
      rows: 5
      placeholder: ''
    third_party_settings: {  }
hidden:
  created: true
  status: true
