<<<<<<< HEAD
uuid: d76a1780-5c82-4091-8b35-6841a270969c
=======
uuid: 20cddb33-919c-43ec-9c9c-f5d63706fbbc
>>>>>>> main
langcode: es
status: true
dependencies:
  config:
    - field.field.paragraph.lib_banner_promo_icons.field_lib_heading
    - field.field.paragraph.lib_banner_promo_icons.field_lib_hero_style
    - field.field.paragraph.lib_banner_promo_icons.field_lib_link
    - field.field.paragraph.lib_banner_promo_icons.field_lib_media_image
    - field.field.paragraph.lib_banner_promo_icons.field_lib_p_items
    - field.field.paragraph.lib_banner_promo_icons.field_lib_summary
    - paragraphs.paragraphs_type.lib_banner_promo_icons
  module:
    - link
    - media_library
    - paragraphs
<<<<<<< HEAD
=======
    - paragraphs_features
>>>>>>> main
id: paragraph.lib_banner_promo_icons.default
targetEntityType: paragraph
bundle: lib_banner_promo_icons
mode: default
content:
  field_lib_heading:
    type: string_textfield
    weight: 1
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  field_lib_hero_style:
    type: options_select
    weight: 5
    region: content
    settings: {  }
    third_party_settings: {  }
  field_lib_link:
    type: link_default
    weight: 3
    region: content
    settings:
      placeholder_url: ''
      placeholder_title: ''
    third_party_settings: {  }
  field_lib_media_image:
    type: media_library_widget
    weight: 0
    region: content
    settings:
      media_types: {  }
    third_party_settings: {  }
  field_lib_p_items:
    type: paragraphs
    weight: 4
    region: content
    settings:
      title: Card
      title_plural: Cards
      edit_mode: open
      closed_mode: summary
<<<<<<< HEAD
      autocollapse: none
=======
      autocollapse: all
>>>>>>> main
      closed_mode_threshold: 0
      add_mode: dropdown
      form_display_mode: lib_card_icon
      default_paragraph_type: lib_card
      features:
        add_above: '0'
        collapse_edit_all: collapse_edit_all
        duplicate: duplicate
<<<<<<< HEAD
    third_party_settings: {  }
=======
    third_party_settings:
      paragraphs_features:
        add_in_between: false
        add_in_between_link_count: 3
        delete_confirmation: false
        split_text: false
        show_drag_and_drop: true
>>>>>>> main
  field_lib_summary:
    type: string_textarea
    weight: 2
    region: content
    settings:
      rows: 5
      placeholder: ''
    third_party_settings: {  }
hidden:
  created: true
  status: true
