<<<<<<< HEAD
uuid: f15ee58d-7fee-4c3c-9d9f-e510a6113f72
=======
uuid: 4061fa95-23ef-40b5-95f8-2364f6e67978
>>>>>>> main
langcode: es
status: true
dependencies:
  module:
    - lightning_core
    - paragraphs
third_party_settings:
  lightning_core:
    description: ''
id: paragraph.lib_icon_card
label: 'Icon card'
targetEntityType: paragraph
cache: true
