<<<<<<< HEAD
uuid: 739b7cdd-19bd-460c-8c34-1f208aafcb8b
=======
uuid: 633e2a05-fe34-4d60-983c-17577c1efe9f
>>>>>>> main
langcode: es
status: true
dependencies:
  config:
    - core.entity_form_mode.media.media_library
    - field.field.media.vector_image.field_media_in_library
    - field.field.media.vector_image.field_media_svg
    - media.type.vector_image
<<<<<<< HEAD
=======
  module:
    - svg_image_field
_core:
  default_config_hash: pYvwyK4bwTN7ZRt7j8EE7UYjQHWYobhNNP5ZFPJFESM
>>>>>>> main
id: media.vector_image.media_library
targetEntityType: media
bundle: vector_image
mode: media_library
content:
<<<<<<< HEAD
  name:
    type: string_textfield
    weight: 0
    region: content
    settings:
      size: 60
=======
  field_media_svg:
    type: svg_image_field_widget
    weight: 0
    region: content
    settings:
      progress_indicator: throbber
      preview_image_max_width: 300
      preview_image_max_height: 300
    third_party_settings: {  }
  langcode:
    type: language_select
    weight: 2
    region: content
    settings:
      include_locked: true
    third_party_settings: {  }
  revision_log_message:
    type: string_textarea
    weight: 25
    region: content
    settings:
      rows: 4
>>>>>>> main
      placeholder: ''
    third_party_settings: {  }
hidden:
  created: true
  field_media_in_library: true
<<<<<<< HEAD
  field_media_svg: true
  langcode: true
  path: true
  revision_log_message: true
=======
  name: true
  path: true
>>>>>>> main
  status: true
  uid: true
