<<<<<<< HEAD
uuid: 4fc23ae1-6264-4a60-afcd-7f476ea558ce
=======
uuid: b3ceac44-3581-4a52-b839-0b7b5e7875ee
>>>>>>> main
langcode: es
status: true
dependencies:
  config:
    - field.field.media.remote_video.field_media_in_library
    - field.field.media.remote_video.field_media_oembed_video
    - media.type.remote_video
  module:
    - media
id: media.remote_video.default
targetEntityType: media
bundle: remote_video
mode: default
content:
  field_media_oembed_video:
    type: oembed
    label: visually_hidden
    settings:
      max_width: 0
      max_height: 0
    third_party_settings: {  }
    weight: 0
    region: content
hidden:
  addtoany: true
  created: true
  field_media_in_library: true
  langcode: true
  name: true
  search_api_excerpt: true
  thumbnail: true
  uid: true
