<<<<<<< HEAD
uuid: 834b8a49-497f-4ba9-9cb5-ab8641a8441e
=======
uuid: a0a48cfd-7539-45e0-932c-9e7b1fb594e7
>>>>>>> main
langcode: es
status: true
dependencies:
  config:
    - field.field.taxonomy_term.talleres_chevrolet.field_aixis
    - field.field.taxonomy_term.talleres_chevrolet.field_ciudad
    - field.field.taxonomy_term.talleres_chevrolet.field_cod_ciudad
    - field.field.taxonomy_term.talleres_chevrolet.field_codtaller
    - field.field.taxonomy_term.talleres_chevrolet.field_direccion
    - field.field.taxonomy_term.talleres_chevrolet.field_email
    - field.field.taxonomy_term.talleres_chevrolet.field_nit
    - field.field.taxonomy_term.talleres_chevrolet.field_sucursal
    - field.field.taxonomy_term.talleres_chevrolet.field_telefono
    - taxonomy.vocabulary.talleres_chevrolet
  module:
    - manage_display
    - text
id: taxonomy_term.talleres_chevrolet.default
targetEntityType: taxonomy_term
bundle: talleres_chevrolet
mode: default
content:
  description:
    type: text_default
    label: hidden
    settings: {  }
    third_party_settings: {  }
    weight: 0
    region: content
  field_aixis:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 2
    region: content
  field_ciudad:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
<<<<<<< HEAD
    weight: 5
=======
    weight: 1
>>>>>>> main
    region: content
  field_cod_ciudad:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
<<<<<<< HEAD
    weight: 6
=======
    weight: 3
>>>>>>> main
    region: content
  field_codtaller:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
<<<<<<< HEAD
    weight: 1
=======
    weight: 4
>>>>>>> main
    region: content
  field_direccion:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
<<<<<<< HEAD
    weight: 4
=======
    weight: 5
>>>>>>> main
    region: content
  field_email:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
<<<<<<< HEAD
    weight: 7
=======
    weight: 6
>>>>>>> main
    region: content
  field_nit:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
<<<<<<< HEAD
    weight: 3
=======
    weight: 7
>>>>>>> main
    region: content
  field_sucursal:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
<<<<<<< HEAD
    weight: 9
=======
    weight: 8
>>>>>>> main
    region: content
  field_telefono:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
<<<<<<< HEAD
    weight: 8
=======
    weight: 9
>>>>>>> main
    region: content
  name:
    type: title
    label: hidden
    settings:
      linked: true
      tag: h2
    third_party_settings: {  }
    weight: -49
    region: content
hidden:
  langcode: true
  search_api_excerpt: true
