<<<<<<< HEAD
uuid: c3365682-19da-4a3e-b6ec-24e8f28d4525
=======
uuid: 04782aba-dffd-4386-90b9-3d6e6e82464f
>>>>>>> main
langcode: es
status: true
dependencies:
  config:
    - field.field.paragraph.lib_tabs.field_lib_p_items
    - paragraphs.paragraphs_type.lib_tabs
  module:
    - entity_reference_revisions
id: paragraph.lib_tabs.default
targetEntityType: paragraph
bundle: lib_tabs
mode: default
content:
  field_lib_p_items:
    type: entity_reference_revisions_entity_view
    label: hidden
    settings:
      view_mode: default
      link: ''
    third_party_settings: {  }
    weight: 0
    region: content
hidden:
  search_api_excerpt: true
