<<<<<<< HEAD
uuid: 7c091133-cda5-4995-aae0-78e93febd9b7
=======
uuid: ef10f76a-b146-4b28-b9a8-4cd54c304d1c
>>>>>>> main
langcode: es
status: true
dependencies:
  module:
    - lightning_core
    - paragraphs
third_party_settings:
  lightning_core:
    description: ''
id: paragraph.lib_plan
label: Plan
targetEntityType: paragraph
cache: true
