<<<<<<< HEAD
uuid: fe6c8ae8-c591-41bd-aa66-853e9dd9a7a8
=======
uuid: 747c8af4-74eb-4393-8883-1b3a872c9728
>>>>>>> main
langcode: es
status: true
dependencies:
  config:
    - field.field.paragraph.lib_hero_carousel.field_lib_p_items
    - paragraphs.paragraphs_type.lib_hero_carousel
  module:
    - paragraphs
<<<<<<< HEAD
=======
    - paragraphs_features
>>>>>>> main
id: paragraph.lib_hero_carousel.default
targetEntityType: paragraph
bundle: lib_hero_carousel
mode: default
content:
  field_lib_p_items:
    type: paragraphs
    weight: 0
    region: content
    settings:
      title: Item
      title_plural: Items
      edit_mode: closed
      closed_mode: summary
      autocollapse: all
      closed_mode_threshold: 0
      add_mode: dropdown
      form_display_mode: default
      default_paragraph_type: lib_hero
      features:
        add_above: '0'
        collapse_edit_all: collapse_edit_all
        duplicate: duplicate
<<<<<<< HEAD
    third_party_settings: {  }
=======
    third_party_settings:
      paragraphs_features:
        add_in_between: false
        add_in_between_link_count: 3
        delete_confirmation: false
        split_text: false
        show_drag_and_drop: true
>>>>>>> main
hidden:
  created: true
  status: true
