<<<<<<< HEAD
uuid: 8286faf2-c848-444b-80aa-585c743646bf
=======
uuid: bd67d57f-e42f-4d6d-9263-c2780db1d3d9
>>>>>>> main
langcode: es
status: true
dependencies:
  config:
    - field.field.paragraph.lib_card.field_lib_body
    - field.field.paragraph.lib_card.field_lib_heading
    - field.field.paragraph.lib_card.field_lib_item_list
    - field.field.paragraph.lib_card.field_lib_link
    - field.field.paragraph.lib_card.field_lib_media_icon
    - field.field.paragraph.lib_card.field_lib_media_image
    - paragraphs.paragraphs_type.lib_card
  module:
    - link
    - media_library
    - text
id: paragraph.lib_card.default
targetEntityType: paragraph
bundle: lib_card
mode: default
content:
  field_lib_body:
    type: text_textarea
    weight: 1
    region: content
    settings:
      rows: 5
      placeholder: ''
    third_party_settings: {  }
  field_lib_heading:
    type: string_textfield
    weight: 0
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  field_lib_item_list:
    type: string_textfield
    weight: 4
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  field_lib_link:
    type: link_default
    weight: 2
    region: content
    settings:
      placeholder_url: ''
      placeholder_title: ''
    third_party_settings: {  }
  field_lib_media_image:
    type: media_library_widget
    weight: 3
    region: content
    settings:
      media_types: {  }
    third_party_settings: {  }
hidden:
  created: true
  field_lib_media_icon: true
  status: true
