<<<<<<< HEAD
uuid: bc0a0487-3dea-42c5-bd0b-79fab75fd8c6
=======
uuid: 42730d3d-32d8-4d8d-8ccc-08de065d6e09
>>>>>>> main
langcode: es
status: true
dependencies:
  module:
    - lightning_core
    - paragraphs
third_party_settings:
  lightning_core:
    description: ''
id: paragraph.plan
label: Plan
targetEntityType: paragraph
cache: true
