<<<<<<< HEAD
uuid: ea809601-ccf6-4167-92b3-67d03a780d6b
=======
uuid: a44931d7-256f-46a7-bc8e-c3e313215808
>>>>>>> main
langcode: es
status: true
dependencies:
  config:
    - field.storage.paragraph.field_lib_media_image
    - media.type.image
    - paragraphs.paragraphs_type.lib_card
id: paragraph.lib_card.field_lib_media_image
field_name: field_lib_media_image
entity_type: paragraph
bundle: lib_card
label: Imagen
description: ''
required: false
<<<<<<< HEAD
translatable: true
=======
translatable: false
>>>>>>> main
default_value: {  }
default_value_callback: ''
settings:
  handler: 'default:media'
  handler_settings:
    target_bundles:
      image: image
    sort:
      field: _none
      direction: ASC
    auto_create: false
    auto_create_bundle: ''
field_type: entity_reference
