<<<<<<< HEAD
uuid: 6517a196-f8a4-4eb6-81b8-633adc8d044e
=======
uuid: d399b08f-387a-4894-8fb8-63d62b7defd3
>>>>>>> main
langcode: es
status: true
dependencies:
  config:
    - field.storage.taxonomy_term.field_cod_ciudad
    - taxonomy.vocabulary.talleres_chevrolet
id: taxonomy_term.talleres_chevrolet.field_cod_ciudad
field_name: field_cod_ciudad
entity_type: taxonomy_term
bundle: talleres_chevrolet
label: 'Codigo ciudad'
description: ''
<<<<<<< HEAD
required: false
=======
required: true
>>>>>>> main
translatable: false
default_value: {  }
default_value_callback: ''
settings: {  }
field_type: string
