<<<<<<< HEAD
uuid: 8c935c6d-2fa2-492c-b636-6c8016a05cd6
=======
uuid: 81cb0d2d-9b4f-4bc3-a065-b56fed2e15e4
>>>>>>> main
langcode: es
status: true
dependencies:
  config:
    - field.storage.paragraph.field_lib_summary
    - paragraphs.paragraphs_type.lib_card_list
id: paragraph.lib_card_list.field_lib_summary
field_name: field_lib_summary
entity_type: paragraph
bundle: lib_card_list
label: Summary
description: ''
required: false
<<<<<<< HEAD
translatable: true
=======
translatable: false
>>>>>>> main
default_value: {  }
default_value_callback: ''
settings: {  }
field_type: string_long
