<<<<<<< HEAD
uuid: d0ec8383-3adf-40e3-8338-685b7e540587
=======
uuid: a9cf2a85-cc70-4d0a-bae7-4a98787d3381
>>>>>>> main
langcode: es
status: true
dependencies:
  config:
    - field.storage.paragraph.field_lib_heading
    - paragraphs.paragraphs_type.lib_hero
id: paragraph.lib_hero.field_lib_heading
field_name: field_lib_heading
entity_type: paragraph
bundle: lib_hero
label: TÃ­tulo
description: ''
required: false
translatable: true
default_value: {  }
default_value_callback: ''
settings: {  }
field_type: string
