<<<<<<< HEAD
uuid: d34798f0-3307-452e-8e61-c857b24cd1de
=======
uuid: 266df2b2-12c5-4ad6-9c99-8352bc0f0d6c
>>>>>>> main
langcode: es
status: true
dependencies:
  config:
    - field.storage.paragraph.field_lib_columns
    - paragraphs.paragraphs_type.lib_card_list_out
  module:
    - options
id: paragraph.lib_card_list_out.field_lib_columns
field_name: field_lib_columns
entity_type: paragraph
bundle: lib_card_list_out
label: 'No. Columnas'
description: ''
<<<<<<< HEAD
required: false
translatable: false
=======
required: true
translatable: true
>>>>>>> main
default_value:
  -
    value: '3'
default_value_callback: ''
settings: {  }
field_type: list_string
