<<<<<<< HEAD
uuid: 902a8ce4-47c9-4369-94e0-f1f12df3384d
=======
uuid: b5c24e24-3e34-4060-8b2a-3536782dce65
>>>>>>> main
langcode: es
status: true
dependencies:
  config:
    - field.storage.taxonomy_term.field_telefono
    - taxonomy.vocabulary.talleres_chevrolet
id: taxonomy_term.talleres_chevrolet.field_telefono
field_name: field_telefono
entity_type: taxonomy_term
bundle: talleres_chevrolet
label: Telefono
description: ''
<<<<<<< HEAD
required: false
=======
required: true
>>>>>>> main
translatable: false
default_value: {  }
default_value_callback: ''
settings: {  }
field_type: string
