<<<<<<< HEAD
uuid: 2628f727-9ba7-4ed7-a844-0e6ac51fa24b
=======
uuid: c202fb70-f1e1-4c22-ab60-11fb9303f754
>>>>>>> main
langcode: es
status: true
dependencies:
  config:
    - field.storage.paragraph.field_lib_heading
    - paragraphs.paragraphs_type.lib_tab_item
id: paragraph.lib_tab_item.field_lib_heading
field_name: field_lib_heading
entity_type: paragraph
bundle: lib_tab_item
label: TÃ­tulo
description: ''
required: false
translatable: true
default_value: {  }
default_value_callback: ''
settings: {  }
field_type: string
