<<<<<<< HEAD
uuid: 3eb278ff-53f7-4fbf-b241-8237744094c5
=======
uuid: bc6e4f65-a710-47e0-863a-1b9f9572ff97
>>>>>>> main
langcode: es
status: true
dependencies:
  config:
    - field.storage.paragraph.field_lib_heading
    - paragraphs.paragraphs_type.lib_card_list_out
id: paragraph.lib_card_list_out.field_lib_heading
field_name: field_lib_heading
entity_type: paragraph
bundle: lib_card_list_out
label: TÃ­tulo
description: ''
required: false
translatable: true
default_value: {  }
default_value_callback: ''
settings: {  }
field_type: string
