<<<<<<< HEAD
uuid: 8cf30c44-fee8-4552-a390-d2a64ff10b70
=======
uuid: 431bd297-bad6-4103-afb5-6190cb69a816
>>>>>>> main
langcode: es
status: true
dependencies:
  config:
    - field.storage.paragraph.field_lib_heading
    - paragraphs.paragraphs_type.card_list_mmedia
id: paragraph.card_list_mmedia.field_lib_heading
field_name: field_lib_heading
entity_type: paragraph
bundle: card_list_mmedia
label: TÃ­tulo
description: ''
<<<<<<< HEAD
required: false
=======
required: true
>>>>>>> main
translatable: true
default_value: {  }
default_value_callback: ''
settings: {  }
field_type: string
