<<<<<<< HEAD
uuid: 2f866a5a-00ca-4b03-bf72-a9a17c31ac78
=======
uuid: ce92d9f9-99fd-4349-803f-48d47fc65385
>>>>>>> main
langcode: es
status: true
dependencies:
  config:
    - field.storage.paragraph.field_lib_media_image
    - media.type.image
    - paragraphs.paragraphs_type.banner_cards
id: paragraph.banner_cards.field_lib_media_image
field_name: field_lib_media_image
entity_type: paragraph
bundle: banner_cards
label: Banner
description: ''
<<<<<<< HEAD
required: false
=======
required: true
>>>>>>> main
translatable: true
default_value: {  }
default_value_callback: ''
settings:
  handler: 'default:media'
  handler_settings:
    target_bundles:
      image: image
    sort:
      field: _none
      direction: ASC
    auto_create: false
    auto_create_bundle: ''
field_type: entity_reference
