<<<<<<< HEAD
uuid: 1a7ebd10-69c8-481d-969b-2c62fde37893
=======
uuid: e17e639c-3974-4f9c-bc32-4047b4394b94
>>>>>>> main
langcode: es
status: true
dependencies:
  module:
    - taxonomy
id: taxonomy_term.field_direccion
field_name: field_direccion
entity_type: taxonomy_term
type: string
settings:
  max_length: 255
  case_sensitive: false
  is_ascii: false
module: core
locked: false
cardinality: 1
translatable: true
indexes: {  }
persist_with_no_fields: false
custom_storage: false
