<<<<<<< HEAD
uuid: 6a1c7d47-0b39-4a68-929e-47b69bb939a4
=======
uuid: 04da69b7-4e98-4503-96e9-5f4dc2569bb8
>>>>>>> main
langcode: es
status: true
dependencies:
  config:
    - field.storage.paragraph.field_lib_link
    - paragraphs.paragraphs_type.lib_hero
  module:
    - link
id: paragraph.lib_hero.field_lib_link
field_name: field_lib_link
entity_type: paragraph
bundle: lib_hero
label: Enlace
description: ''
required: false
translatable: true
default_value: {  }
default_value_callback: ''
settings:
  title: 1
  link_type: 17
field_type: link
