<<<<<<< HEAD
uuid: 97ad790a-aec3-406a-8377-f7b85d136d91
=======
uuid: 7fc7c9d9-bd35-4085-b450-792e0672f034
>>>>>>> main
langcode: es
status: true
dependencies:
  config:
    - field.storage.paragraph.field_lib_heading
    - paragraphs.paragraphs_type.lib_banner_promo_icons
id: paragraph.lib_banner_promo_icons.field_lib_heading
field_name: field_lib_heading
entity_type: paragraph
bundle: lib_banner_promo_icons
label: TÃ­tulo
description: ''
<<<<<<< HEAD
required: false
=======
required: true
>>>>>>> main
translatable: true
default_value: {  }
default_value_callback: ''
settings: {  }
field_type: string
