<<<<<<< HEAD
uuid: 3bd61030-9d6b-4bdd-8fe3-fa2794abf8b9
=======
uuid: 09a635e8-4064-4d3e-ae09-74589f1774fa
>>>>>>> main
langcode: es
status: true
dependencies:
  config:
    - field.storage.paragraph.field_lib_item_list
    - paragraphs.paragraphs_type.lib_card
id: paragraph.lib_card.field_lib_item_list
field_name: field_lib_item_list
entity_type: paragraph
bundle: lib_card
label: 'Lista items'
description: ''
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings: {  }
field_type: string
