<<<<<<< HEAD
uuid: 5bac44a0-12ce-4ad3-8ef8-5a1e15c4ec04
=======
uuid: 6c35d881-3807-4d5e-be20-5f7402402432
>>>>>>> main
langcode: es
status: true
dependencies:
  config:
    - field.storage.paragraph.field_lib_heading
    - paragraphs.paragraphs_type.lib_card
id: paragraph.lib_card.field_lib_heading
field_name: field_lib_heading
entity_type: paragraph
bundle: lib_card
label: TÃ­tulo
description: ''
required: false
<<<<<<< HEAD
translatable: false
=======
translatable: true
>>>>>>> main
default_value: {  }
default_value_callback: ''
settings: {  }
field_type: string
