<<<<<<< HEAD
uuid: 4fbec0e9-e9a8-4b6b-ae2c-99e08ca7a425
=======
uuid: bdbc9cd9-86f6-4585-9412-2759cea6abb8
>>>>>>> main
langcode: es
status: true
dependencies:
  config:
    - field.storage.taxonomy_term.field_codtaller
    - taxonomy.vocabulary.talleres_chevrolet
id: taxonomy_term.talleres_chevrolet.field_codtaller
field_name: field_codtaller
entity_type: taxonomy_term
bundle: talleres_chevrolet
label: 'Codigo taller'
description: ''
<<<<<<< HEAD
required: false
=======
required: true
>>>>>>> main
translatable: false
default_value: {  }
default_value_callback: ''
settings: {  }
field_type: string
