<<<<<<< HEAD
uuid: 4e63bfd7-2122-462d-bc3e-09f791120ee3
=======
uuid: b7f2e510-a61a-4b55-8e5a-c5966fd6d1c6
>>>>>>> main
langcode: es
status: true
dependencies:
  config:
    - field.storage.media.field_media_in_library
    - media.type.remote_video
id: media.remote_video.field_media_in_library
field_name: field_media_in_library
entity_type: media
bundle: remote_video
label: 'Show in media library'
description: ''
required: false
translatable: true
default_value:
  -
    value: 1
default_value_callback: ''
settings:
  on_label: 'Shown in media library'
  off_label: 'Hidden in media library'
field_type: boolean
