<<<<<<< HEAD
uuid: de0559f6-7217-4307-96be-983acb4bea49
=======
uuid: 247c428c-a4ff-473e-9c60-6765978e5bb9
>>>>>>> main
langcode: es
status: true
dependencies:
  module:
    - taxonomy
id: taxonomy_term.field_cod_ciudad
field_name: field_cod_ciudad
entity_type: taxonomy_term
type: string
settings:
  max_length: 255
  case_sensitive: false
  is_ascii: false
module: core
locked: false
cardinality: 1
translatable: true
indexes: {  }
persist_with_no_fields: false
custom_storage: false
