<<<<<<< HEAD
uuid: 035f47d8-f85e-40b0-9fe0-e678f202104d
=======
uuid: 65c75c5d-69b1-4dc7-befb-db8aadf0fa64
>>>>>>> main
langcode: es
status: true
dependencies:
  config:
    - field.storage.paragraph.field_lib_heading
    - paragraphs.paragraphs_type.card_media
id: paragraph.card_media.field_lib_heading
field_name: field_lib_heading
entity_type: paragraph
bundle: card_media
label: TÃ­tulo
description: ''
required: false
<<<<<<< HEAD
translatable: true
=======
translatable: false
>>>>>>> main
default_value: {  }
default_value_callback: ''
settings: {  }
field_type: string
