<<<<<<< HEAD
uuid: 0b1e9737-2721-4648-9de6-6a61a6de1d4c
=======
uuid: 604eda47-3889-47b9-a18a-c1721a8fb071
>>>>>>> main
langcode: es
status: true
dependencies:
  config:
    - field.storage.paragraph.field_lib_hero_style
    - paragraphs.paragraphs_type.lib_banner_promo_icons
  module:
    - options
id: paragraph.lib_banner_promo_icons.field_lib_hero_style
field_name: field_lib_hero_style
entity_type: paragraph
bundle: lib_banner_promo_icons
label: Estilo
description: ''
<<<<<<< HEAD
required: false
=======
required: true
>>>>>>> main
translatable: false
default_value:
  -
    value: hero2
default_value_callback: ''
settings: {  }
field_type: list_string
