<<<<<<< HEAD
uuid: 7654162f-7161-4d1e-8d34-7f6778344456
=======
uuid: ad5c3bed-4f2f-4fe5-8fea-765e2de83444
>>>>>>> main
langcode: es
status: true
dependencies:
  config:
    - field.storage.paragraph.field_lib_heading
    - paragraphs.paragraphs_type.banner_cards
id: paragraph.banner_cards.field_lib_heading
field_name: field_lib_heading
entity_type: paragraph
bundle: banner_cards
label: TÃ­tulo
description: ''
required: false
translatable: true
default_value: {  }
default_value_callback: ''
settings: {  }
field_type: string
