<<<<<<< HEAD
uuid: 78b63e8e-cfc3-49d1-8111-d1de5801c850
=======
uuid: 6fc18d6c-6af1-459e-b5cf-06cc2f46f855
>>>>>>> main
langcode: es
status: true
dependencies:
  config:
    - field.storage.paragraph.field_lib_heading
    - paragraphs.paragraphs_type.plan_list
id: paragraph.plan_list.field_lib_heading
field_name: field_lib_heading
entity_type: paragraph
bundle: plan_list
label: TÃ­tulo
description: ''
required: false
translatable: true
default_value: {  }
default_value_callback: ''
settings: {  }
field_type: string
