<<<<<<< HEAD
uuid: c8ebac12-e669-4db1-ae6e-02513ddf7444
=======
uuid: a00df070-ef8d-411a-93cc-809ea0b8083a
>>>>>>> main
langcode: es
status: true
dependencies:
  config:
    - field.storage.taxonomy_term.field_email
    - taxonomy.vocabulary.talleres_chevrolet
id: taxonomy_term.talleres_chevrolet.field_email
field_name: field_email
entity_type: taxonomy_term
bundle: talleres_chevrolet
label: Email
description: ''
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings: {  }
field_type: string
