_core:
  default_config_hash: 7J75jee6uT-qT16hDiNTHOtRFPgAz_ppCBdl7GTo-As
langcode: es
cache:
  http:
    s_maxage: 86400
    404_max_age: 86400
    302_max_age: 86400
    301_max_age: 86400
    5xx_max_age: 86400
    stale_while_revalidate: 86400
    stale_if_error: 86400
    vary: ''
<<<<<<< HEAD
  surrogate:
    maxage: 86400
    nostore: null
=======
    mustrevalidate: 0
    nocache: 0
    nostore: 0
    cookieextra: null
  surrogate:
    maxage: 86400
    nostore: false
>>>>>>> main
