<<<<<<< HEAD
uuid: 9979d5e8-0450-44ab-abb4-fbd6fe6c5f2f
=======
uuid: b6cef180-cd40-442a-868f-f0c33ec6557a
>>>>>>> main
langcode: es
status: true
dependencies:
  config:
    - media.type.vector_image
id: media.vector_image
target_entity_type_id: media
target_bundle: vector_image
default_langcode: site_default
language_alterable: false
