plan_list:
  662: '662'
  663: '663'
map_distance: '7'
preferential_title: 'Red Médica Preferencial Liberty Seguros'
preferential_description: 'En Liberty Seguros existimos para ayudarte a disfrutar el presente y mirar con confianza el futuro. La Red Médica Preferencial te permite a ti y a tu familia acceder a una red de instituciones de altísima calidad, infraestructura y servicios.'
description_662: 'Selecciona esta opción si tienes una de las siguientes pólizas de Liberty Salud: Total Help MD o Salud Esencial'
description_663: 'Selecciona esta opción si tienes una Póliza Liberty Accidentes Personales'
langcode: es
