features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 0
  path: themes/custom/liberty_public/logo.svg
favicon:
  use_default: 0
  path: themes/custom/liberty_public/favicon.ico
  mimetype: image/vnd.microsoft.icon
