ace_editor: 1.0.0
acquia_connector: 1.16.0
acquia_purge: 1.0.0
acquia_search: 3.0.4
addtoany: 1.10.0
admin_toolbar: 1.25.0
admin_toolbar_search: 2.4.0
admin_toolbar_tools: 1.25.0
ape: 1.5.0
autologout: 1.0.0
ban: 9.3.3
better_exposed_filters: 5.0.0-beta1
blazy: 1.0.0-rc3
block: 8.6.3
block_class: 1.0.0
block_content: 8.6.3
breakpoint: 8.6.3
captcha: 1.0.0-beta1
checklistapi: 1.8.0
ckeditor: 8.6.3
ckeditor_videodetector: 1.0.0
condition_query: 1.2.0
config: 8.6.3
config_delete: 1.17.0
config_filter: 2.4.0
config_ignore: 2.3.0
consumers: 1.2.0
contact: 8.6.3
contact_storage: 1.0.0-beta9
content_moderation: 8.6.3
content_translation: 8.9.13
contextual: 8.6.3
core_context: 0.0.0
crop: 2.0.0-rc1
ctools: 3.0.0
ctools_block: 3.0.0
datetime: 8.6.3
dblog: 8.9.13
devel: 2.1.0
devel_generate: 1.2.0
devel_php: 1.0.0
diff: 1.0.0-rc2
dropzonejs: 2.0.0-alpha3
ds: 3.1.0
ds_switch_view_mode: 3.1.0
dynamic_page_cache: 8.7.3
easy_breadcrumb: 1.8.0
editor: 8.6.3
editor_advanced_link: 1.8.0
embed: 1.0.0
entity_block: 1.0.0-beta1
entity_browser: 2.0.0-alpha2
entity_clone: 1.0.0-alpha2
entity_embed: 1.0.0-beta2
entity_reference: 8.6.3
entity_reference_revisions: 1.6.0
entityqueue: 1.2.0
facets: 1.2.0
field: 8.6.3
field_group: 1.0.0
field_ui: 8.6.3
file: 8.6.3
filter: 8.6.3
geolocation: 1.11.0
geolocation_google_maps: 3.2.0
geolocation_google_places_api: 1.11.0
google_analytics: 2.4.0
help: 8.6.3
history: 8.6.3
honeypot: 1.29.0
http_cache_control: 2.0.0
image: 8.6.3
image_captcha: 1.0.0-beta1
image_widget_crop: 2.2.0
inline_entity_form: 1.0.0-rc1
jquery_ui: 0.0.0
jquery_ui_accordion: 1.1.0
jquery_ui_autocomplete: 1.1.0
jquery_ui_datepicker: 1.0.0
jquery_ui_draggable: 0.0.0
jquery_ui_droppable: 0.0.0
jquery_ui_menu: 1.1.0
jquery_ui_slider: 1.1.0
jquery_ui_tabs: 1.1.0
jquery_ui_touch_punch: 1.0.0
jsonapi: 1.23.0
kint: 2.1.0
layout_builder: 8.7.3
layout_builder_restrictions: 0.0.0
layout_builder_st: 1.0.0-alpha1
layout_builder_styles: 0.0.0
layout_discovery: 8.6.3
layout_library: 0.0.0
li_news: 0.0.0
lib_ajax: 0.0.0
lib_cf: 0.0.0
lib_core: 0.0.0
lib_ls: 1.0.0
lib_microsites: 0.0.0
lib_migrate: 0.0.0
lib_quoting: 0.0.0
lib_red_medica: 0.0.0
lib_rm: 0.0.0
liberty_claims: 0.0.0
libraries: 3.0.0-alpha1
lightning: 3.202.0
lightning_api: 2.7.0
lightning_contact_form: 3.3.0
lightning_core: 3.3.0
lightning_install: 3.202.0
lightning_landing_page: 1.4.0
lightning_layout: 1.4.0
lightning_media: 3.1.0
lightning_media_audio: 3.1.0
lightning_media_bulk_upload: 3.1.0
lightning_media_document: 3.1.0
lightning_media_image: 3.1.0
lightning_media_instagram: 3.1.0
lightning_media_slideshow: 3.1.0
lightning_media_twitter: 3.1.0
lightning_media_video: 3.1.0
lightning_page: 3.3.0
lightning_roles: 3.3.0
lightning_scheduler: 3.1.0
lightning_search: 3.3.0
lightning_workflow: 3.1.0
link: 8.6.3
link_attributes: 0.0.0
link_class: 1.3.0
locale: 8.6.4
maillog: 1.0.0-beta1
mailsystem: 4.3.0
manage_display: 1.0.0-beta2
maxlength: 1.0.0-rc1
media: 8.6.3
media_entity_instagram: 2.0.0-alpha1
media_entity_twitter: 2.0.0-alpha2
media_library: 8.6.3
memcache: 2.0.0
menu_link_attributes: 1.0.0
menu_link_content: 8.6.3
menu_ui: 8.6.3
metatag: 1.7.0
metatag_google_cse: 1.7.0
metatag_open_graph: 1.7.0
metatag_twitter_cards: 1.7.0
migrate: 8.6.5
migrate_csv: 0.0.0
migrate_spreadsheet: 1.0.0
migratewebform: 0.0.0
mimemail: 1.0.0-alpha4
moderation_sidebar: 1.1.0
node: 8.6.3
oauth2_client: 2.0.0-beta3
openapi: 1.0.0-beta2
openapi_jsonapi: 0.0.0
openapi_rest: 0.0.0
openapi_ui: 1.0.0-rc1
openapi_ui_redoc: 1.0.0-rc2
openapi_ui_swagger: 1.0.0-rc2
options: 8.6.3
page_cache: 8.6.3
panelizer: 4.1.0
panelizer_quickedit: 4.1.0
panels: 4.3.0
panels_ipe: 4.3.0
paragraphs: 1.5.0
paragraphs_browser: 1.0.0-rc1
password_policy: 3.0.0-alpha4
password_policy_characters: 3.0.0-alpha4
password_policy_length: 3.0.0-alpha4
path: 8.6.3
path_alias: 8.x-dev
pathauto: 1.3.0
profile_switcher: 1.0.0-alpha5
purge: 3.0.0-beta8
purge_drush: 3.0.0-beta8
purge_processor_cron: 3.0.0-beta8
purge_processor_lateruntime: 3.0.0-beta8
purge_queuer_coretags: 3.0.0-beta8
purge_tokens: 3.0.0-beta8
purge_ui: 3.0.0-beta8
quickedit: 8.6.3
rdf: 8.6.3
recaptcha: 3.0.0
redirect: 1.3.0
remove_http_headers: 1.0.0-alpha5
responsive_image: 8.6.4
rest: 8.7.3
restui: 1.17.0
schemata: 1.0.0-alpha5
schemata_json_schema: 1.0.0-alpha5
search: 8.6.5
search_api: 1.11.0
search_api_autocomplete: 1.1.0
search_api_db: 1.11.0
search_api_solr: 4.2.0
search_api_solr_autocomplete: 4.2.6
seckit: 1.1.0
seo_checklist: 4.1.0
serialization: 8.6.3
shortcut: 8.6.3
shs: 1.0.0-alpha4
simple_oauth: 3.11.0
simple_oauth_extras: 3.11.0
simple_sitemap: 3.0.0
slick: 1.0.0
slick_entityreference: 1.1.0
slick_ui: 1.1.0
slick_views: 2.0.0-alpha1
social_media: 1.3.0
social_media_links: 2.6.0
statistics: 8.6.5
svg_image: 1.8.0
svg_image_field: 2.1.0
syslog: 8.6.16
system: 8.6.3
taxonomy: 8.6.3
tb_megamenu: 0.0.0
text: 8.6.3
token: 1.5.0
toolbar: 8.6.3
twig_field_value: 1.1.0
twig_tweak: 2.1.0
update: 8.x-dev
user: 8.6.3
video_embed_field: 2.0.0
video_embed_media: 2.0.0
views: 8.6.3
views_bulk_operations: 3.2.0
views_field_view: 1.0.0-beta2
views_infinite_scroll: 1.5.0
views_ui: 8.9.13
viewsreference: 2.0.0-alpha4
we_megamenu: 1.4.0
webform: 5.0.0-rc29
webform_access: 5.0.0-rc29
webform_bootstrap: 5.0.0-rc29
webform_image_select: 5.0.0-rc29
webform_node: 5.0.0-rc29
webform_rest: 2.0.0-beta2
webform_submission_export_import: 5.29.0
webform_submissions_delete: 1.0.0
webform_templates: 5.0.0-rc29
webform_ui: 5.0.0-rc29
workflows: 8.6.3
yaml_editor: 1.0.0
