<<<<<<< HEAD
=======
langcode: es
>>>>>>> main
entity_type_groups:
  node:
    landing_page:
      basic: basic
    page:
      basic: basic
    product:
      open_graph: open_graph
      twitter_cards: twitter_cards
