<<<<<<< HEAD
uuid: 4e63a02a-fbb3-4b47-bc30-a1aa7a9dc48c
=======
uuid: f0d3355d-ff7c-4cbe-9e36-dd0a736d6280
>>>>>>> main
langcode: es
status: true
dependencies:
  module:
    - lightning_workflow
    - menu_ui
third_party_settings:
  menu_ui:
    available_menus:
      - main
    parent: 'main:'
  lightning_workflow:
    workflow: editorial
name: Informes
type: informes
description: 'Landing con contenido exclusivo para el tipo de rol informes'
help: ''
new_revision: true
preview_mode: 1
display_submitted: true
