<<<<<<< HEAD
uuid: 07c21871-6333-40e7-b4fd-8d6d31045359
=======
uuid: 554091fd-5de6-4bbb-bc50-1fed3433a7c6
>>>>>>> main
langcode: es
status: true
dependencies: {  }
id: lib_tabs
label: Tabs
icon_uuid: null
icon_default: null
description: 'Liberty Pesta√±as.'
behavior_plugins: {  }
