<<<<<<< HEAD
uuid: f7bd65d1-d368-4b78-b265-38f528a01dec
=======
uuid: 0736d039-2785-48db-8270-59e1c54e50bf
>>>>>>> main
langcode: es
status: true
dependencies: {  }
id: card_grid_accordion
label: 'Card Grid Accordion'
icon_uuid: null
icon_default: null
description: ''
behavior_plugins: {  }
