<<<<<<< HEAD
uuid: 35158170-e84f-403d-a723-1361ee106429
=======
uuid: 28c729c7-adb6-4e15-8ac7-42554777557e
>>>>>>> main
langcode: es
status: true
dependencies: {  }
id: plan_list
label: 'Plan List'
icon_uuid: null
icon_default: null
<<<<<<< HEAD
description: ''
=======
description: 'Liberty Plan List.'
>>>>>>> main
behavior_plugins: {  }
