channels:
  -
    id: purgers
    grants:
      - 0
      - 2
      - 3
  -
    id: queue
    grants:
      - 0
      - 2
      - 3
  -
    id: diagnostics
    grants:
      - 3
  -
    id: purger_acquia_purge_5e096374f4
    grants:
      - 0
      - 2
      - 3
