_core:
  default_config_hash: 3fc8Vgfn3iZIANxHSYu6bUQ9WoZ38PR5G7jgQt5YOyM
langcode: es
headers_to_remove:
  - X-Generator
  - X-Drupal-Dynamic-Cache
dependencies:
  enforced:
    module:
      - remove_http_headers
