_core:
  default_config_hash: iIf5HmjnxW8tLdod1EQ19q4RQ5mkg-r5wBn2QFmitr8
langcode: es
access_token_expiration: 300
authorization_code_expiration: 300
refresh_token_expiration: 1209600
token_cron_batch_size: 0
remember_clients: true
use_implicit: false
disable_openid_connect: false
